package com.xyan.admin.model;

import com.xyan.frame.base.model.BaseModel;

/**
 * @Description: 配置实体类 xy_preference
 * @Author：wangming
 * @email：18136442251@163.com
 * @Date:2016-06-14 11:02:12
 */
public class PreferenceModel extends BaseModel {

	/**
	 * This field was generated by CodeGenerator. This field corresponds to the
	 * database column xy_preference.NAME_. 名称
	 */
	private String name;

	/**
	 * This field was generated by CodeGenerator. This field corresponds to the
	 * database column xy_preference.KIND_. 类别
	 */
	private String kind;

	/**
	 * This field was generated by CodeGenerator. This field corresponds to the
	 * database column xy_preference.VALUE_. 值
	 */
	private String value;

	/**
	 * This field was generated by CodeGenerator. This field corresponds to the
	 * database column xy_preference.REMARK_. 备注
	 */
	private String remark;
	
	public PreferenceModel() {
		
	}

	public PreferenceModel(String name, String kind) {
		super();
		this.name = name;
		this.kind = kind;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getKind() {
		return kind;
	}

	public void setKind(String kind) {
		this.kind = kind;
	}

	public String getValue() {
		return value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	
}