package com.xyan.frame.grab.model;

import com.xyan.frame.base.model.BaseModel;

/**
 * @Description: 实体类 xy_head
 * @Author：wangming
 * @Date:2016-04-14 15:45:43
 */
public class HeadModel extends BaseModel {

	/**
	 * This field was generated by CodeGenerator. This field corresponds to the
	 * database column xy_head.NAME. 头名称
	 */
	private String name;

	/**
	 * This field was generated by CodeGenerator. This field corresponds to the
	 * database column xy_head.VALUE. 值
	 */
	private String value;

	/**
	 * This field was generated by CodeGenerator. This field corresponds to the
	 * database column xy_head.PAGE_ID. 关联页面的ID
	 */
	private Long pageId;
	
	public HeadModel() {
		
	}
	
	public HeadModel(String name,String value) {
		this.name=name;
		this.value=value;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getName() {
		return this.name;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public String getValue() {
		return this.value;
	}

	public void setPageId(Long pageId) {
		this.pageId = pageId;
	}

	public Long getPageId() {
		return this.pageId;
	}

}