package com.xyan.frame.grab.model;

import java.util.Date;
import java.util.List;

import javax.persistence.Transient;

import com.xyan.frame.base.model.BaseModel;

/**
 * @Description: 抓取的页面 实体类 xy_page
 * @Author：wangming
 * @Date:2016-04-14 15:42:46
 */
public class PageModel extends BaseModel {

	/**
	 * This field was generated by CodeGenerator. This field corresponds to the
	 * database column xy_page.URL. 抓取的url地址
	 */
	private String url;

	/**
	 * This field was generated by CodeGenerator. This field corresponds to the
	 * database column xy_page.STATUS. 抓取的状态码
	 */
	private Integer status;

	/**
	 * This field was generated by CodeGenerator. This field corresponds to the
	 * database column xy_page.RESULT. 抓取到的页面内容
	 */
	private String result;

	/**
	 * This field was generated by CodeGenerator. This field corresponds to the
	 * database column xy_page.GRAB_DATE. 抓取时间
	 */
	private Date grabDate;
	
	@Transient
	private List<HeadModel> heads;

	public void setUrl(String url) {
		this.url = url;
	}

	public String getUrl() {
		return this.url;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setResult(String result) {
		this.result = result;
	}

	public String getResult() {
		return this.result;
	}

	public void setGrabDate(Date grabDate) {
		this.grabDate = grabDate;
	}

	public Date getGrabDate() {
		return this.grabDate;
	}

	public List<HeadModel> getHeads() {
		return heads;
	}

	public void setHeads(List<HeadModel> heads) {
		this.heads = heads;
	}

}