package com.xyan.blog.model;

import com.xyan.frame.base.model.BaseModel;

/**
 * @Description: 实体类 xy_article_type
 * @Author：wangming
 * @email：w18855525068@163.com
 * @Date:2016-06-07 14:11:45
 */
public class ArticleTypeModel extends BaseModel {

	/**
	 * This field was generated by CodeGenerator. This field corresponds to the
	 * database column xy_article_type.NAME. 名称
	 */
	private String name;

	/**
	 * This field was generated by CodeGenerator. This field corresponds to the
	 * database column xy_article_type.PID. 父级ID(根为-1)
	 */
	private Long pId;

	private boolean isParent;
	private boolean open;
	private boolean isHidden;
	private boolean halfCheck;
	/**
	 * This method was generated by CodeGenerator. 名称
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by CodeGenerator. 名称
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * This method was generated by CodeGenerator. 父级ID(根为-1)
	 */
	public void setpId(Long pId) {
		this.pId = pId;
	}

	/**
	 * This method was generated by CodeGenerator. 父级ID(根为-1)
	 */
	public Long getpId() {
		return this.pId;
	}

	public boolean getIsParent() {
		return isParent;
	}

	public void setIsParent(boolean isParent) {
		this.isParent = isParent;
	}

	public boolean isOpen() {
		return open;
	}

	public void setOpen(boolean open) {
		this.open = open;
	}

	public boolean isHidden() {
		return isHidden;
	}

	public void setHidden(boolean isHidden) {
		this.isHidden = isHidden;
	}

	public boolean isHalfCheck() {
		return halfCheck;
	}

	public void setHalfCheck(boolean halfCheck) {
		this.halfCheck = halfCheck;
	}

}