package com.xyan.blog.model;

import java.util.Date;

import com.xyan.frame.base.model.BaseModel;

/**
 * @Description: 文章（博客） 实体类 xy_article
 * @Author：wangming
 * @Date:2016-05-17 13:34:13
 */
public class ArticleModel extends BaseModel {

	/**
	 * This field was generated by CodeGenerator. This field corresponds to the
	 * database column xy_article.TITLE. 标题
	 */
	private String title;

	/**
	 * This field was generated by CodeGenerator. This field corresponds to the
	 * database column xy_article.CONTENT. 内容
	 */
	private String content;

	/**
	 * This field was generated by CodeGenerator. This field corresponds to the
	 * database column xy_article.USER_ID. 作者
	 */
	private Long userId;

	/**
	 * This field was generated by CodeGenerator. This field corresponds to the
	 * database column xy_article.CREATE_TIME. 创建时间
	 */
	private Date createTime;

	/**
	 * This field was generated by CodeGenerator. This field corresponds to the
	 * database column xy_article.UPDATE_TIME. 最后修改时间
	 */
	private Date updateTime;

	/**
	 * This field was generated by CodeGenerator. This field corresponds to the
	 * database column xy_article.TYPE_ID. 类型
	 */
	private Long typeId;

	/**
	 * This field was generated by CodeGenerator. This field corresponds to the
	 * database column xy_article.KEY_WORD. 关键词（多个用，隔开）
	 */
	private String keyWord;

	/**
	 * This field was generated by CodeGenerator. This field corresponds to the
	 * database column xy_article.PRODUCE1. 介绍1
	 */
	private String produce1;

	/**
	 * This field was generated by CodeGenerator. This field corresponds to the
	 * database column xy_article.READ_COUNT. 阅读次数
	 */
	private Integer readCount;

	/**
	 * This field was generated by CodeGenerator. This field corresponds to the
	 * database column xy_article.COMMENT_COUNT. 评论次数
	 */
	private Integer commentCount;

	/**
	 * This field was generated by CodeGenerator. This field corresponds to the
	 * database column xy_article.PRODUCE2. 介绍2
	 */
	private String produce2;

	/**
	 * This field was generated by CodeGenerator. This field corresponds to the
	 * database column xy_article.IMG_URL. 图片地址
	 */
	private String imgUrl;
	/**
	 * This method was generated by CodeGenerator. 标题
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by CodeGenerator. 标题
	 */
	public String getTitle() {
		return this.title;
	}

	/**
	 * This method was generated by CodeGenerator. 内容
	 */
	public void setContent(String content) {
		this.content = content;
	}

	/**
	 * This method was generated by CodeGenerator. 内容
	 */
	public String getContent() {
		return this.content;
	}

	/**
	 * This method was generated by CodeGenerator. 作者
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by CodeGenerator. 作者
	 */
	public Long getUserId() {
		return this.userId;
	}

	/**
	 * This method was generated by CodeGenerator. 创建时间
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by CodeGenerator. 创建时间
	 */
	public Date getCreateTime() {
		return this.createTime;
	}

	/**
	 * This method was generated by CodeGenerator. 最后修改时间
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by CodeGenerator. 最后修改时间
	 */
	public Date getUpdateTime() {
		return this.updateTime;
	}

	/**
	 * This method was generated by CodeGenerator. 类型
	 */
	public void setTypeId(Long typeId) {
		this.typeId = typeId;
	}

	/**
	 * This method was generated by CodeGenerator. 类型
	 */
	public Long getTypeId() {
		return this.typeId;
	}

	/**
	 * This method was generated by CodeGenerator. 关键词（多个用，隔开）
	 */
	public void setKeyWord(String keyWord) {
		this.keyWord = keyWord;
	}

	/**
	 * This method was generated by CodeGenerator. 关键词（多个用，隔开）
	 */
	public String getKeyWord() {
		return this.keyWord;
	}

	/**
	 * This method was generated by CodeGenerator. 介绍1
	 */
	public void setProduce1(String produce1) {
		this.produce1 = produce1;
	}

	/**
	 * This method was generated by CodeGenerator. 介绍1
	 */
	public String getProduce1() {
		return this.produce1;
	}

	/**
	 * This method was generated by CodeGenerator. 阅读次数
	 */
	public void setReadCount(Integer readCount) {
		this.readCount = readCount;
	}

	/**
	 * This method was generated by CodeGenerator. 阅读次数
	 */
	public Integer getReadCount() {
		return this.readCount;
	}

	/**
	 * This method was generated by CodeGenerator. 评论次数
	 */
	public void setCommentCount(Integer commentCount) {
		this.commentCount = commentCount;
	}

	/**
	 * This method was generated by CodeGenerator. 评论次数
	 */
	public Integer getCommentCount() {
		return this.commentCount;
	}

	/**
	 * This method was generated by CodeGenerator. 介绍2
	 */
	public void setProduce2(String produce2) {
		this.produce2 = produce2;
	}

	/**
	 * This method was generated by CodeGenerator. 介绍2
	 */
	public String getProduce2() {
		return this.produce2;
	}

	public String getImgUrl() {
		return imgUrl;
	}

	public void setImgUrl(String imgUrl) {
		this.imgUrl = imgUrl;
	}

}