package com.xyan.blog.model;

import com.xyan.frame.base.model.BaseModel;

/**
 * @Description: 字典--实体类
 * @Author：wangming
 * @email：18136442251@163.com
 * @Date:2016-06-16 15:07:58
 */
public class DictModel extends BaseModel {

	/**
	 * This field was generated by CodeGenerator. This field corresponds to the
	 * database column xy_dict.NAME. 名称
	 */
	private String name;

	/**
	 * This field was generated by CodeGenerator. This field corresponds to the
	 * database column xy_dict.type. 类别
	 */
	private String type;
	
	/**
	 * This field was generated by CodeGenerator. This field corresponds to the
	 * database column xy_dict.remark. 备注
	 */
	private String remark;

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}
	
	
	



}