package com.xyan.blog.model;


import java.util.Date;

import com.xyan.frame.base.model.BaseModel;


/**
 *@Description: 消息  实体类 
 *				xy_message
 *@Author：wangming
 *@email：w18855525068@163.com
 *@Date:2016-05-30 15:25:02
 */
public class MessageModel extends BaseModel{
		
	/**
	 * This field was generated by  CodeGenerator. 
	 * This field corresponds to the database column xy_message.FROM.
	 *发自
	 */
	private Long source;
		
	/**
	 * This field was generated by  CodeGenerator. 
	 * This field corresponds to the database column xy_message.TO.
	 *目标，公共发言为-1
	 */
	private Long dest;
		
	/**
	 * This field was generated by  CodeGenerator. 
	 * This field corresponds to the database column xy_message.TITLE.
	 *标题
	 */
	private String title;
		
	/**
	 * This field was generated by  CodeGenerator. 
	 * This field corresponds to the database column xy_message.CONTENT.
	 *内容
	 */
	private String content;
		
	/**
	 * This field was generated by  CodeGenerator. 
	 * This field corresponds to the database column xy_message.CREATE_TIME.
	 *创建时间
	 */
	private Date createTime;
	
	/**
	 * This field was generated by  CodeGenerator. 
	 * This field corresponds to the database column xy_message.merge.
	 *是否紧急留言
	 */
	private String merge;
		
	
	/**
	 * This method was generated by  CodeGenerator. 
	 *发自
	 */
	public void setSource(Long source){
		this.source=source;
	}
	
	/**
	 * This method was generated by  CodeGenerator. 
	 *发自
	 */
	public Long getSource(){
		return this.source;
	}
	
	/**
	 * This method was generated by  CodeGenerator. 
	 *目标，公共发言为-1
	 */
	public void setDest(Long dest){
		if(dest==null){
			dest=-1L;
		}
		this.dest=dest;
	}
	
	/**
	 * This method was generated by  CodeGenerator. 
	 *目标，公共发言为-1
	 */
	public Long getDest(){
		return this.dest;
	}
	
	/**
	 * This method was generated by  CodeGenerator. 
	 *标题
	 */
	public void setTitle(String title){
		this.title=title;
	}
	
	/**
	 * This method was generated by  CodeGenerator. 
	 *标题
	 */
	public String getTitle(){
		return this.title;
	}
	
	/**
	 * This method was generated by  CodeGenerator. 
	 *内容
	 */
	public void setContent(String content){
		this.content=content;
	}
	
	/**
	 * This method was generated by  CodeGenerator. 
	 *内容
	 */
	public String getContent(){
		return this.content;
	}
	
	/**
	 * This method was generated by  CodeGenerator. 
	 *创建时间
	 */
	public void setCreateTime(Date createTime){
		this.createTime=createTime;
	}
	
	/**
	 * This method was generated by  CodeGenerator. 
	 *创建时间
	 */
	public Date getCreateTime(){
		return this.createTime;
	}

	/**
	 * This method was generated by  CodeGenerator. 
	 *是否紧急留言
	 */
	public String getMerge() {
		return merge;
	}

	/**
	 * This method was generated by  CodeGenerator. 
	 *是否紧急留言
	 */
	public void setMerge(String merge) {
		this.merge = merge;
	}
		
	
}