package com.xyan.frame.feature.log.model;

import java.util.Date;

import com.xyan.frame.base.model.BaseModel;

/**
 * @Description: 日志实体类 xy_log
 * @Author：wangming
 * @Date:2016-04-14 17:18:14
 */
public class LogModel {
	
	private String id;

	/**
	 * This field was generated by CodeGenerator. This field corresponds to the
	 * database column xy_log.LOG_DATE. log时间
	 */
	private Date logDate;

	/**
	 * This field was generated by CodeGenerator. This field corresponds to the
	 * database column xy_log.LOG_TYPE. log类别
	 * @see com.xyan.common.enums.LogType
	 */
	private String logType;
	/**
	 * This field was generated by CodeGenerator. This field corresponds to the
	 * database column xy_log.CONTENT. 记录内容
	 */
	private String content;

	public LogModel() {

	}
	
	public LogModel(Date logDate,String content) {
		this.logDate=logDate;
		this.content=content;
	}

	public void setLogDate(Date logDate) {
		this.logDate = logDate;
	}

	public Date getLogDate() {
		return this.logDate;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getContent() {
		return this.content;
	}

	public String getLogType() {
		return logType;
	}

	public void setLogType(String logType) {
		this.logType = logType;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}
	
	
}